# Generated by Django 4.2.7 on 2023-11-23 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_delete_carts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='carts',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
        ),
    ]
